import { Hono } from "hono";
import { changeTabEditMode, changeTabName, changeTabVisibility, createTab, generateAccessCode, getAllTabs, getTabDetail, joinTab, removeTab, } from "../controllers/tab.controllers";
import { authMiddleware } from "../middlewares/authMiddleware";
const tabRoutes = new Hono();
tabRoutes.use(authMiddleware);
tabRoutes.get("/all", getAllTabs);
tabRoutes.post("/create", createTab);
tabRoutes.post("/join/:accessCode", joinTab);
tabRoutes.post("/:tabId/remove", removeTab);
tabRoutes.put("/:tabId/name", changeTabName);
tabRoutes.put("/:tabId/visibility", changeTabVisibility);
tabRoutes.post("/:tabId/accessCode", generateAccessCode);
tabRoutes.post("/:tabId/editable", changeTabEditMode);
tabRoutes.get("/:tabId/detail", getTabDetail);
export default tabRoutes;
